// ---------------------------------------------------------------------------
// POST /api/memory/canonicalize/apply
//
// Applies entity canonicalization proposals generated by the dry-run step.
// Each proposal row with proposalAction 'review_alias' (resolved facts with
// a new alias to register) will be written to memory_entity_aliases via
// EntityCanonicalizationStore.upsertAlias().
//
// Pass dryRun: true to preview counts without writing.
// ---------------------------------------------------------------------------

import type { FastifyPluginAsync } from 'fastify';
import type { Pool } from 'pg';
import type { Logger } from 'pino';

import type { EntityCanonicalizationProposalRow } from '../../memory/entity-canonicalization-proposals.js';
import { EntityCanonicalizationStore } from '../../memory/entity-canonicalization-store.js';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type MemoryCanonicalizeApplyRoutesOptions = {
  pool: Pool;
  logger: Logger;
};

type ApplyRequestBody = {
  proposals: EntityCanonicalizationProposalRow[];
  dryRun?: boolean;
};

type ApplyErrorEntry = {
  factId: string;
  canonicalId: string;
  alias: string;
  error: string;
};

type ApplyResponseBody = {
  ok: true;
  dryRun: boolean;
  applied: number;
  skipped: number;
  errors: ApplyErrorEntry[];
};

// ---------------------------------------------------------------------------
// Route plugin
// ---------------------------------------------------------------------------

export const memoryCanonicalizeApplyRoutes: FastifyPluginAsync<
  MemoryCanonicalizeApplyRoutesOptions
> = async (app, opts) => {
  const { pool, logger } = opts;
  const store = new EntityCanonicalizationStore({ pool, logger });

  app.post<{ Body: ApplyRequestBody }>('/', async (request, reply) => {
    const body = request.body ?? {};
    const proposals: EntityCanonicalizationProposalRow[] = Array.isArray(body.proposals)
      ? body.proposals
      : [];
    const dryRun = body.dryRun === true;

    const actionable = proposals.filter(
      (p) => p.proposalAction === 'review_alias' && p.canonicalId !== null,
    );

    const skipped = proposals.length - actionable.length;
    let applied = 0;
    const errors: ApplyErrorEntry[] = [];

    if (!dryRun) {
      for (const proposal of actionable) {
        const canonicalId = proposal.canonicalId as string;
        try {
          await store.upsertAlias({
            canonicalId,
            alias: proposal.entityName,
            sourceJson: { factId: proposal.factId },
          });
          applied++;
        } catch (err: unknown) {
          const message = err instanceof Error ? err.message : String(err);
          logger.warn({ factId: proposal.factId, canonicalId, err }, 'Failed to apply alias');
          errors.push({ factId: proposal.factId, canonicalId, alias: proposal.entityName, error: message });
        }
      }
    } else {
      applied = actionable.length;
    }

    logger.info(
      { dryRun, total: proposals.length, actionable: actionable.length, applied, skipped, errors: errors.length },
      'Canonicalization apply completed',
    );

    return reply.code(200).send({
      ok: true,
      dryRun,
      applied,
      skipped,
      errors,
    } satisfies ApplyResponseBody);
  });
};
