import type {
  AgentConfig,
  DispatchSignature,
  DispatchVerificationConfig,
  SafetyDecisionRequest,
} from '@agentctl/shared';
import { AgentError, SAFETY_DECISIONS, verifyDispatchPayloadSignature } from '@agentctl/shared';
import type { FastifyInstance, FastifyPluginOptions } from 'fastify';
import type { Logger } from 'pino';

import type { AgentPool } from '../../runtime/agent-pool.js';

type AgentRouteOptions = FastifyPluginOptions & {
  pool: AgentPool;
  machineId: string;
  logger: Logger;
  getDispatchVerificationConfig?: () => DispatchVerificationConfig | null;
};

type StartAgentBody = {
  prompt: string;
  config?: AgentConfig;
  projectPath?: string;
  /** Run ID assigned by the control plane for this execution. Stored on the agent instance for audit correlation. */
  runId?: string;
  /** URL of the control plane. Used by the agent to POST completion callbacks when a run finishes. */
  controlPlaneUrl?: string;
  /** Session ID to resume a previous agent session instead of starting fresh. */
  resumeSession?: string;
  /** Decrypted API credential forwarded by the control plane. */
  accountCredential?: string | null;
  /** Provider of the forwarded API credential. */
  accountProvider?: string | null;
  /** Ed25519 signature envelope generated by the control plane. */
  dispatchSignature?: DispatchSignature;
};

type StopAgentBody = {
  graceful?: boolean;
};

type SteerAgentBody = {
  message: string;
};

type SafetyDecisionBody = SafetyDecisionRequest;

type AgentIdParams = {
  id: string;
};

const ERROR_STATUS_MAP: Record<string, number> = {
  AGENT_NOT_FOUND: 404,
  AGENT_EXISTS: 409,
  POOL_FULL: 503,
  INVALID_TRANSITION: 409,
  AGENT_STILL_RUNNING: 409,
  SAFETY_BLOCKED: 409,
  SAFETY_DECISION_NOT_PENDING: 409,
  STEER_NOT_RUNNING: 409,
};

function errorToStatusCode(err: unknown): number {
  if (err instanceof AgentError) {
    return ERROR_STATUS_MAP[err.code] ?? 500;
  }
  return 500;
}

function errorToResponse(err: unknown): {
  error: string;
  code: string;
  context?: Record<string, unknown>;
} {
  if (err instanceof AgentError) {
    return {
      error: err.message,
      code: err.code,
      context: err.context,
    };
  }

  const message = err instanceof Error ? err.message : String(err);
  return { error: message, code: 'INTERNAL_ERROR' };
}

export async function agentRoutes(app: FastifyInstance, options: AgentRouteOptions): Promise<void> {
  const { pool, machineId, logger, getDispatchVerificationConfig } = options;

  // GET /api/agents — list all agents in the pool
  app.get('/', async (_request, reply) => {
    const agents = pool.listAgents();
    return reply.send({
      agents,
      count: agents.length,
      maxConcurrent: pool.getMaxConcurrent(),
    });
  });

  // GET /api/agents/stats — aggregate pool statistics
  app.get('/stats', async (_request, reply) => {
    const stats = pool.getAgentStats();
    return reply.send(stats);
  });

  // GET /api/agents/:id — get single agent details
  app.get<{ Params: AgentIdParams }>('/:id', async (request, reply) => {
    const { id } = request.params;
    const instance = pool.getAgent(id);

    if (!instance) {
      return reply.status(404).send({
        error: `Agent '${id}' not found`,
        code: 'AGENT_NOT_FOUND',
      });
    }

    return reply.send(instance.toJSON());
  });

  // POST /api/agents/:id/start — create agent in pool (if needed) and start it
  app.post<{ Params: AgentIdParams; Body: StartAgentBody }>(
    '/:id/start',
    async (request, reply) => {
      const { id } = request.params;
      const unsignedDispatchPayload = { ...request.body };
      const {
        prompt,
        config,
        projectPath,
        runId,
        controlPlaneUrl,
        resumeSession,
        dispatchSignature,
      } = request.body;
      delete unsignedDispatchPayload.dispatchSignature;

      const dispatchVerificationConfig = getDispatchVerificationConfig?.() ?? null;
      if (dispatchVerificationConfig) {
        if (!dispatchSignature) {
          logger.warn(
            { agentId: id, machineId },
            'Rejected dispatch without signature while verification key is configured',
          );
          return reply.status(401).send({
            error: 'Dispatch signature required',
            code: 'DISPATCH_SIGNATURE_REQUIRED',
          });
        }

        if (
          !verifyDispatchPayloadSignature(unsignedDispatchPayload, dispatchSignature, {
            publicKey: dispatchVerificationConfig.publicKey,
            agentId: id,
            machineId,
          })
        ) {
          logger.warn(
            { agentId: id, machineId, dispatchSignature },
            'Rejected dispatch with invalid signature',
          );
          return reply.status(401).send({
            error: 'Invalid dispatch signature',
            code: 'INVALID_DISPATCH_SIGNATURE',
          });
        }
      }

      if (!prompt || typeof prompt !== 'string' || prompt.trim().length === 0) {
        return reply.status(400).send({
          error: 'A non-empty "prompt" string is required',
          code: 'INVALID_INPUT',
        });
      }

      if (prompt.length > 32_000) {
        return reply.status(400).send({
          error: 'PROMPT_TOO_LONG',
          message: 'Prompt must be under 32,000 characters',
        });
      }

      try {
        // Remove stale instance from pool if it's in a terminal state.
        // This ensures each new run gets a fresh instance with the correct
        // runId, controlPlaneUrl, and clean event listeners / output buffer.
        const existing = pool.getAgent(id);
        if (existing) {
          const existingStatus = existing.getStatus();
          if (
            existingStatus === 'stopped' ||
            existingStatus === 'error' ||
            existingStatus === 'timeout'
          ) {
            await pool.removeAgent(id);
          }
        }

        let instance = pool.getAgent(id);

        if (!instance) {
          instance = await pool.createAgent({
            agentId: id,
            machineId,
            config: config ?? {},
            projectPath: projectPath ?? process.cwd(),
            logger,
            runId,
            controlPlaneUrl,
            resumeSession,
          });
        }

        await instance.start(prompt);

        return reply.status(200).send({
          ok: true,
          agentId: id,
          sessionId: instance.getSessionId(),
          status: instance.getStatus(),
        });
      } catch (err) {
        const statusCode = errorToStatusCode(err);
        return reply.status(statusCode).send(errorToResponse(err));
      }
    },
  );

  app.post<{ Params: AgentIdParams; Body: SafetyDecisionBody }>(
    '/:id/safety-decision',
    async (request, reply) => {
      const { id } = request.params;
      const { decision } = request.body ?? {};

      if (!decision || !SAFETY_DECISIONS.includes(decision)) {
        return reply.status(400).send({
          error: 'A valid "decision" is required',
          code: 'INVALID_INPUT',
        });
      }

      const instance = pool.getAgent(id);

      if (!instance) {
        return reply.status(404).send({
          error: `Agent '${id}' not found`,
          code: 'AGENT_NOT_FOUND',
        });
      }

      try {
        await instance.applySafetyDecision(decision);

        return reply.status(200).send({
          ok: true,
          agentId: id,
          sessionId: instance.getSessionId(),
          status: instance.getStatus(),
        });
      } catch (err) {
        const statusCode = errorToStatusCode(err);
        return reply.status(statusCode).send(errorToResponse(err));
      }
    },
  );

  // POST /api/agents/:id/steer — inject steering guidance into a running agent
  app.post<{ Params: AgentIdParams; Body: SteerAgentBody }>(
    '/:id/steer',
    async (request, reply) => {
      const { id } = request.params;
      const { message } = request.body ?? {};

      if (!message || typeof message !== 'string' || message.trim().length === 0) {
        return reply.status(400).send({
          error: 'A non-empty "message" string is required',
          code: 'INVALID_INPUT',
        });
      }

      if (message.length > 32_000) {
        return reply.status(400).send({
          error: 'STEER_MESSAGE_TOO_LONG',
          message: 'Steering message must be under 32,000 characters',
        });
      }

      const instance = pool.getAgent(id);

      if (!instance) {
        return reply.status(404).send({
          error: `Agent '${id}' not found`,
          code: 'AGENT_NOT_FOUND',
        });
      }

      try {
        const result = await instance.steer(message);

        return reply.status(200).send({
          ok: result.accepted,
          agentId: id,
          accepted: result.accepted,
          ...(result.reason ? { reason: result.reason } : {}),
        });
      } catch (err) {
        const statusCode = errorToStatusCode(err);
        return reply.status(statusCode).send(errorToResponse(err));
      }
    },
  );

  // POST /api/agents/:id/stop — stop a running agent
  app.post<{ Params: AgentIdParams; Body: StopAgentBody }>('/:id/stop', async (request, reply) => {
    const { id } = request.params;
    const { graceful = true } = request.body ?? {};

    try {
      await pool.stopAgent(id, graceful);

      const instance = pool.getAgent(id);
      return reply.status(200).send({
        ok: true,
        agentId: id,
        status: instance?.getStatus() ?? 'stopped',
      });
    } catch (err) {
      const statusCode = errorToStatusCode(err);
      return reply.status(statusCode).send(errorToResponse(err));
    }
  });

  // DELETE /api/agents/:id — remove a stopped agent from the pool
  app.delete<{ Params: AgentIdParams }>('/:id', async (request, reply) => {
    const { id } = request.params;

    try {
      const removed = await pool.removeAgent(id);

      if (!removed) {
        return reply.status(404).send({
          error: `Agent '${id}' not found`,
          code: 'AGENT_NOT_FOUND',
        });
      }

      return reply.status(200).send({
        ok: true,
        agentId: id,
      });
    } catch (err) {
      const statusCode = errorToStatusCode(err);
      return reply.status(statusCode).send(errorToResponse(err));
    }
  });
}
