#!/bin/bash
set -euo pipefail

# =============================================================================
# AgentCTL Mesh Node Setup
#
# Bootstraps a new machine into the agentctl mesh. Checks prerequisites,
# creates a local PostgreSQL database, detects the Tailscale IP, and writes
# .env.mesh with all required configuration.
#
# Usage:
#   ./scripts/setup-mesh-node.sh
#   pnpm build
#   pm2 start infra/pm2/ecosystem.mesh.config.cjs
# =============================================================================

echo "=== AgentCTL Mesh Node Setup ==="
echo ""

# ── Prerequisite checks ────────────────────────────────────────────────────

MISSING=()
for cmd in psql redis-cli node pnpm; do
  if ! command -v "$cmd" >/dev/null 2>&1; then
    MISSING+=("$cmd")
  fi
done

# Tailscale is optional — mesh works over localhost without it.
HAS_TAILSCALE=false
if command -v tailscale >/dev/null 2>&1; then
  HAS_TAILSCALE=true
fi

if [ ${#MISSING[@]} -gt 0 ]; then
  echo "ERROR: Missing required tools: ${MISSING[*]}"
  echo ""
  echo "Install them first:"
  echo "  macOS:  brew install postgresql redis node pnpm"
  echo "  Linux:  apt install postgresql redis-server nodejs && npm i -g pnpm"
  exit 1
fi

echo "All prerequisites found."
echo ""

# ── Machine identity ───────────────────────────────────────────────────────

# MACHINE_ID can be overridden via env var; otherwise derive from hostname.
MACHINE_ID="${MACHINE_ID:-$(hostname | tr '[:upper:]' '[:lower:]' | tr -cd 'a-z0-9-')}"

# Detect Tailscale IP (falls back to 127.0.0.1 if Tailscale is not running).
TS_IP="127.0.0.1"
if [ "$HAS_TAILSCALE" = true ]; then
  TS_IP=$(tailscale ip -4 2>/dev/null || echo "127.0.0.1")
fi

echo "Machine ID:    $MACHINE_ID"
echo "Tailscale IP:  $TS_IP"
echo ""

# ── Database ───────────────────────────────────────────────────────────────

DBNAME="${AGENTCTL_DB:-agentctl_mesh}"
PG_PORT="${PG_PORT:-5432}"
PG_USER="${PG_USER:-$(whoami)}"

echo "Database:      $DBNAME (port $PG_PORT, user $PG_USER)"

if psql -U "$PG_USER" -p "$PG_PORT" -lqt 2>/dev/null | cut -d \| -f 1 | grep -qw "$DBNAME"; then
  echo "  Database already exists — skipping creation."
else
  createdb -U "$PG_USER" -p "$PG_PORT" "$DBNAME" 2>/dev/null || {
    echo "ERROR: Failed to create database '$DBNAME'."
    echo "Make sure PostgreSQL is running and user '$PG_USER' has CREATE DATABASE permission."
    exit 1
  }
  echo "  Created database '$DBNAME'."
fi

echo ""

# ── Peer reverse-registration token ────────────────────────────────────────
#
# Every node in the same mesh must share the same SYNC_PEER_REGISTRATION_TOKEN
# so that adding a peer on one node auto-registers the caller on the other.
# Preserve an existing token if .env.mesh already has one; otherwise honour
# $SYNC_PEER_REGISTRATION_TOKEN from the environment (for copying across the
# fleet); finally fall back to generating a fresh one locally.

ENV_FILE=".env.mesh"

EXISTING_TOKEN=""
if [ -f "$ENV_FILE" ]; then
  EXISTING_TOKEN=$(grep -E '^SYNC_PEER_REGISTRATION_TOKEN=' "$ENV_FILE" | head -1 | cut -d= -f2- || true)
fi

if [ -n "$EXISTING_TOKEN" ]; then
  PEER_TOKEN="$EXISTING_TOKEN"
  TOKEN_SOURCE="preserved from existing $ENV_FILE"
elif [ -n "${SYNC_PEER_REGISTRATION_TOKEN:-}" ]; then
  PEER_TOKEN="$SYNC_PEER_REGISTRATION_TOKEN"
  TOKEN_SOURCE="inherited from environment (fleet-wide rollout)"
else
  if ! command -v openssl >/dev/null 2>&1; then
    echo "ERROR: openssl is required to generate SYNC_PEER_REGISTRATION_TOKEN."
    echo "Either install openssl or set SYNC_PEER_REGISTRATION_TOKEN in the env before re-running."
    exit 1
  fi
  PEER_TOKEN=$(openssl rand -hex 32)
  TOKEN_SOURCE="freshly generated — copy to every peer in the mesh"
fi

echo "Peer token:    ${TOKEN_SOURCE}"
echo ""

# ── Write .env.mesh ────────────────────────────────────────────────────────

cat > "$ENV_FILE" << EOF
# AgentCTL Mesh Node Configuration
# Generated by setup-mesh-node.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")

TIER=mesh
MACHINE_ID=$MACHINE_ID
DATABASE_URL=postgresql://$PG_USER@127.0.0.1:$PG_PORT/$DBNAME
REDIS_URL=redis://localhost:6379/0
PORT=8080
WORKER_PORT=9000
CONTROL_PLANE_URL=http://localhost:8080
CONTROL_URL=http://localhost:8080
TAILSCALE_IP=$TS_IP
NODE_ENV=production

# Shared bootstrap token for mesh peer reverse-registration.
# Must match across every node in the mesh — copy this value into each peer's
# .env.mesh (or export SYNC_PEER_REGISTRATION_TOKEN before re-running this
# script on the next node). See .env.mesh.template for details.
SYNC_PEER_REGISTRATION_TOKEN=$PEER_TOKEN

# Uncomment and set if you use encrypted API credentials:
# CREDENTIAL_ENCRYPTION_KEY=

# Uncomment to skip auto-migrations (if run separately):
# SKIP_MIGRATIONS=true
EOF

echo "Wrote $ENV_FILE"
echo ""

# ── Summary ────────────────────────────────────────────────────────────────

echo "=== Setup complete ==="
echo ""
echo "Next steps:"
echo "  1. pnpm install && pnpm build"
echo "  2. pm2 start infra/pm2/ecosystem.mesh.config.cjs"
echo "  3. pm2 save && pm2 startup"
echo ""
echo "Migrations will run automatically on first CP startup."
echo "The node will be discoverable by other mesh peers via Tailscale at $TS_IP."
echo ""
if [ "$TOKEN_SOURCE" = "freshly generated — copy to every peer in the mesh" ]; then
  echo "IMPORTANT: SYNC_PEER_REGISTRATION_TOKEN was freshly generated on this node."
  echo "For reverse-registration to work, EVERY other node must use the same value."
  echo "Copy this command to each peer before re-running setup-mesh-node.sh there:"
  echo ""
  echo "  export SYNC_PEER_REGISTRATION_TOKEN='$PEER_TOKEN'"
  echo ""
fi
